### ISSUE TITLE
fix libgcj build

### ISSUE THREAD

**Issue by rubenvb** [rubenvb/MinGW-w64-build-scripts#17]
libgcj build is broken as it stands. Perhaps worth looking into.

**Comment by rfcclub** [comment]
Hi rubenvb,
I tried your buildscript in recent days with gcc-4.8.1 to build gcj. Though it requires revise abit, it ran very well when producing gcc,objc etc.  And then I tried to build gcj with libjava in i686-w64-mingw32. It failed with some problems as follow:
- termios.h: I commented all part of termios since it can not be used in Windows. It can be fixed later.
- liconv: cross compiler told that it can not solve -liconv. I changed libiconv build to shared but it still inform like that. 
  If you have a look to this, could you please help me by point me a way to let cross compiler recognize -liconv or link static to libiconv.a ?
  Thanks & Best regards,
  Nam

**Comment by rubenvb** [comment]
libgcj is currently not functional on Windows. I seem to remember getting nasty errors related to exceptions in some C++ source file. I'm not interested in fixing this

It might be that both static and shared libiconv needs to be available, there will probably be no way around this and it is a bad thing to link libiconv statically into a libgcj dll. Maybe try configuring GCC with --disable-shared which will build all runtime libs static only.

**Comment by rfcclub** [comment]
The best part I can do up to now is make gcj & gij works OK under some circumstances (gcc-4.7.2) but most of tools from libgcj do not work such as gcj-dbtool.
I describe some hacks were done on gcc source and rubenvb build to make sure that libgcj of gcc-4.8.1 can be build, but not sure that gcj and other tools work well. Hope that someone will have interest to complete it.
- For rubenvb build, just do the build for mingw32mingw32 and mingw32mingw32-dw2 only ( mean i686-w64-mingw32). Of course, those packages need corresponding cross compilers.
- Go to gcc/configure and check so it have no "noconfigdirs libjava" for i23456-mingw\* or something similar.

```
# Disable Java, libgcj or related libraries for some systems.
case "${target}" in
...
  ia64*-*-*vms*)
    noconfigdirs="$noconfigdirs ${libgcj}"
    ;;
  i[3456789]86-w64-mingw*)    
    ;;
  i[3456789]86-*-mingw*)    
    ;;
```
- Go to src/gcc/libjava/ and change configure

```
*-*-mingw*)
    extra_ldflags_libjava="-liconv -L`$PREREQINSTALL`/lib"
```
- Go to src/gcc/libjava and change Makefile.in:
  Find "mode=link" and change libtool as static link ( has 4 position like that )

```
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
    --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
    $(LDFLAGS) -static   -o $@ 
( if you compile on msys, you can alter this part with -ldl -liconv so it does not complain about dlopen and iconv)
```
- The final is change some source to make sure that they are right on windows:
  sysdeps/i386/locks.h

``` javascript
inline static bool
compare_and_swap(volatile obj_addr_t *addr,
         obj_addr_t old,
         obj_addr_t new_val)
{
  #ifdef _WIN32
    return  InterlockedCompareExchange(reinterpret_cast<volatile long*>(addr), static_cast<long>(old), static_cast<long>(new_val));
  #else
    return __sync_bool_compare_and_swap (addr, old, new_val);
  #endif
} 
```

libjava/java/io/natVMConsole.cc: Comment all parts relate to termios.h since Windows does not have termios.h

RESULT:
It will compile successfully, generate libgcj bla bla bla .jar + libgcj tools as static link but they won't work on Windows. They just run and hang. In case of gcj, we can replace ecj1.exe with a good one from MinGW 4.4 but nothing more can do with other libgcj tools. I don't know why ecj1.exe does not work in gcc-4.8.1 :D ( just a C++ newbee) but it seems that gcj has problem when creating VM.
